### ISSUE TITLE
Temperature reading doesn't work

### ISSUE THREAD

**Issue by aruldd** [closedcube/ClosedCube_HDC1010_Arduino#1]
The temperature gets stuck at 125C. This is because the device is not set for Temperature measurement

I fixed this by changing this,

```
void ClosedCube_HDC1010::begin(uint8_t address) {
	_address = address;
	Wire.begin();
	Wire.beginTransmission(_address);
	Wire.write(CONFIGURATION);
	Wire.write(0x0);
	Wire.write(0x0);
	Wire.endTransmission();

}
```

to this
```
void ClosedCube_HDC1010::begin(uint8_t address) {
	_address = address;
	Wire.begin();
	Wire.beginTransmission(_address);
	Wire.write(CONFIGURATION);
	Wire.write(0x1000); // Here
	Wire.write(0x0);
	Wire.endTransmission();

}

**Comment by closedcube** [comment]
Hello,

How did you acquire RH/T measurements : both at the same time or separately?

As per spec:
"(a) Set the acquisition mode to independently measure temperature or humidity by setting Bit[12] to 0."
and you can use either use T (0x00) or RH (0x01) pointer to read the respectively measurement

P.S.
see readData(pointer) in ClosedCube_HDC1010.cpp

**Comment by closedcube** [comment]
Closed: ClosedCube HDC1010 Arduino library supports independent temperature and humidity measurements.

**Comment by paxbat14** [comment]
Always getting temp 125C and RH 100%.
