### ISSUE TITLE
HDC1010 Heater

### ISSUE THREAD

**Issue by tjquick** [closedcube/ClosedCube_HDC1010_Arduino#3]
The HDC1010 has a built in heater. Is there a way to activate it?

**Comment by closedcube** [comment]
HEAT (Heater) is part of Configuration Register and there is not option to change it, except amend the initialisation of the sensor. We will look into the library to add this option shortly.

**Comment by tjquick** [comment]
Thank you! We will be using these units in cave research where humidity is high. The heater will be used to recondition the sensor. I will be ordering 3 more when your store opens again 12/8.


Thanks,

Tom


________________________________

**Comment by closedcube** [comment]
Hello,

Thank you for your patience.
Configuration Register added to HDC1010 Arduino library, please have a look hdc1010demo.ino example for more details how to use Heater.
